export class DicomTagsModel {
  constructor(
    //ajouter les autres tags non relatifs au patient
    public firstName: string,
    public patientName: string,
    public patientGroupLength: string,
    public patientBirthDate: string,
    public patientBirthTime: string,
    public patientSex: string,
    public typeOfPatientID: string,
    public IssuerOfPatientID: string,
    public patientID: string,
    public patientInsurancePlanCodeSequence: string,
    public patientPrimaryLanguageCodeSeq: string,
    public patientPrimaryLanguageCodeModSeq: string,
    public otherPatientIDs: string,
    public otherPatientIDsSequence: string,
    public otherPatientNames: string,
    public patientBirthName: string,
    public patientAge: string,
    public patientSize: string,
    public patientWeight: string,
    public patientAddress: string,
    public insurancePlanIdentification: string,
    public patientMotherBirthName: string,
    public militaryRank: string,
    public BranchOfService: string,
    public medicalRecordLocator: string,
    public medicalAlerts: string,
    public allergies: string,
    public countryOfResidence: string,
    public regionOfResidence: string,
    public patientTelephoneNumbers: string,
    public ethnicGroup: string,
    public occupation: string,
    public smokingStatus: string,
    public additionalPatientHistory: string,
    public lastMenstrualDate: string,
    public patientReligiousPreference: string,
    public patientSpeciesDescription: string,
    public patientSpeciesCodeSerquence: string,
    public patientSexNeutered: string,
    public anatomicalOrientationType: string,
    public patientBreedDescription: string,
    public patientBreedCodeSequence: string,
    public BreedRegistrationNumber: string,
    public BreedRegistryCodeSequence: string,
    public responsiblePerson: string,
    public responsiblePersonRole: string,
    public responsibleOrganization: string,
    public patientComments: string
  ) {}
}
